task: classification

data:
  source: csv
  path: data/passed_test.csv
  target_col: 2
  features_cols: [0, 1]
  split: 
    test_size: [0.7, 0.2, 0.1]
    shuffle: true

model:
  input_size: 2
  layers: [64, 32, 8, 1]
  activation_function: relu
  output_activation: sigmoid

train:
  loss: bce
  optimizer:
    name: adam
    lr: 0.001
    betas: [0.9, 0.999]
  batch_size: 32
  epochs: 100

experiment:
  mode: repeat_seeds
  preprocess: null
  seeds: [10, 11, 12]