task: regression

data:
  source: csv
  path: data/sin_test.csv
  target_col: 1
  features_cols: [0]
  split: 
    test_size: [0.7, 0.2, 0.1]
    shuffle: true

model:
  input_size: 1
  layers: [64, 16, 1]
  activation_function: relu
  output_activation: identity

train:
  loss: mse
  optimizer:
    name: adam
    lr: 0.001
    betas: [0.9, 0.999]
  batch_size: 32
  epochs: 100

experiment:
  mode: repeat_seeds
  preeprocessor: null
  seeds: [42, 43, 44]